### ISSUE TITLE
Change Webhook to Push?

### ISSUE THREAD

**Issue by mMoliere** [majlis-erc/manuForma#16]
The team is finally testing manuForma with some data. One of the first things they asked me about is to shorten the amount of time it takes between submitting their records to GitHub and being able to load it again into manuForma to continue work on it. It seems to me that I am essentially the bottleneck in our workflow, as I need to manually merge the pull requests. One obvious way to shorten the timespan is to push changes to our repository rather than creating pull requests. Do you think that would be advisable or do you see problems with such a change?

**Comment by wsalesky** [comment]
I suppose you could, I don't think I would advise it. The forms are not password protected so anyone can submit data to your github account. I think that opens you up to some possible issues that the pull requests should shield you from. Pull requests also handle possible merge conflicts. 

Another option would be to allow other users the ability to merge a pull request.

**Comment by mMoliere** [comment]
The security issue can be mitigated – we have put the entire domain behind password protection. And we intend to keep it that way in any case because we want to control when the public can access our data.

I guess that merge conflicts could arise. But we could handle those manually if they occur.

I am open to other team members mergin pull requests, but I get the impression that most would rather avoid working with GitHub. What is more we would need someone to be always "on active pull request duty". That would be a big organizational work and these people would have to be able to react quickly.

Overall, to me the benefits of pushing outweigh the disadvantages.

I shall ask Nathan to weigh in, as he is more experienced than me.

**Comment by wsalesky** [comment]
@mMoliere that is fine. If you are comfortable with it, I can make the change. Just let me know.

**Comment by nathangibson** [comment]
Hi @mMoliere and @wsalesky 

Besides the security issues, I think there are also factors regarding versioning, editorial review, and deployment. I can imagine that the "main" branch is the "release" version to be used for displaying one or more manuscript catalogue websites. So that should be a stable, tested, numbered version and you probably want it to have some kind of editorial review also.

I could imagine a solution whereby manuForma loads records from a different branch, say "draft", that is periodically merged manually by an editor via PR into "main." Even then, I'd suppose it may be cleaner if manuForma still uses PRs to the draft branch, but then if we use some kind of GitHub workflow/bot/CI to automatically merge those PRs into the draft branch when they don't have conflicts. This would help with managing conflicts and reverting PRs when needed. In future, it would also be possible to set up additional merge tests if we want to. 

What do you think?

**Comment by mMoliere** [comment]
Hi @nathangibson

This is how I understand your solution and please correct me if I get it wrong:

We let manuForma push its data into branch called "draft" and periodically we merge this branch into the main branch. This way editors could easily access the most recent version of the files they worked on AND we leverage the versioning, review, and deployment capabilities of Github.

**Comment by nathangibson** [comment]
@mMoliere partly -- we could have manuForma push directly to "draft," which in my opinion would be better than pushing directly to "main." 

But I think even better would be if it uses the draft branch the same way it uses main now (loads data from it and does pull requests to it) _but_ pull requests are automatically merged into draft (by a Github bot/workflow so that you don't have to do it manually and have someone constantly on duty).

Using pull requests in my opinion has the advantage that you can more easily track and revert them (you can restore a branch or revert the merge) and conflicts are easier to handle. (If a pull request can't be merged because there is a merge conflict, this only obstructs work on that branch, whereas if you have a conflict for the main/draft branch, everything has to stop until you fix it.) 

Does that make sense? 

PS for auto-merging, the branch would need some kind of status check, but then we could use something like https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-auto-merge-for-pull-requests-in-your-repository and https://github.com/marketplace/actions/auto-merge-pull-request to auto-merge.

**Comment by mMoliere** [comment]
I have discussed the matter further with Gregor and Ronny. 

Surprisingly, Gregor was enticed by my suggestion that the editors merge their own files into GitHub. I am still awaiting Ronny's reply. So, I will keep this issue open for the moment.
