### ISSUE TITLE
ID not displayed

### ISSUE THREAD

**Issue by mMoliere** [majlis-erc/manuForma#487]
@wsalesky In the headline displaying the shelfmark, the record ID is missing – only the square brackets remind us of it.
<img width="1464" alt="Bildschirmfoto 2023-12-22 um 19 01 55" src="https://github.com/majlis-erc/manuForma/assets/73166992/55cfe130-d2ac-495f-8410-7f7aa2ba1215">

**Comment by wsalesky** [comment]
@mMoliere This is because the new idno's are ending with a '/', 
Example:` <idno type="URI">https://jalit.org/manuscript/ARCHES-106/</idno>`
The application expects no trailing slash: /
`<idno type="URI">https://jalit.org/manuscript/ARCHES-106</idno>`

If you are going to routinely have the trailing slashes I can amend the app, but I think it is better practice to remove the trailing slash.

**Comment by mMoliere** [comment]
@wsalesky Thank you for the info. I will amend the idno's and remove the trailing slashes.

**Comment by mMoliere** [comment]
@wsalesky I checked my files. And the error also occurs for entries that have no trailing slashes:

![Screenshot 2024-01-10 at 10-53-31 Edit MS TEI Records](https://github.com/majlis-erc/manuForma/assets/73166992/da5e24c7-48a7-4567-8d13-8de1534766c2)

**Comment by wsalesky** [comment]
Fixed here: https://github.com/majlis-erc/manuForma/pull/497
