### ISSUE TITLE
Relation update fails

### ISSUE THREAD

**Issue by mMoliere** [majlis-erc/manuForma#512]
@wsalesky I noticed that the Relations forms were broken and tried to debug it. But, I can't figure out what's wrong.

Basically, manuForma only displays the collapsible and the attributes without their names. All of the child elements are omitted.

Can you take a look?
![Screenshot 2024-01-24 at 18-10-22 Edit Relation TEI Records](https://github.com/majlis-erc/manuForma/assets/73166992/38daaa51-444d-4b50-b4f5-d5c6209cd6a9)

**Comment by wsalesky** [comment]
@mMoliere I will take a look.

**Comment by wsalesky** [comment]
@mMoliere 
You will need to add this: 
```
<elementSpec ident="body" mode="change">
                        <gloss>*RelationshipTEST</gloss>
                        <gloss type="tei">&lt;body&gt;</gloss>
                        <content>
                            <elementRef key="ab"/>
                        </content>
                    </elementSpec>
```
to here: https://github.com/majlis-erc/manuForma/blob/main/forms/schemas/relations-schema.xml#L84

Because your config.xml for relations calls the body element, so the form looks for a definition in the schema, it is not currently defined in the schema at all, so it can't find the children of the body element... 

Let me know if that does not work (It did on my local copy).
