### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by mMoliere** [majlis-erc/manuForma#611]
@wsalesky In Works appears an error message whenever an author is added using the lookup-feature:

![Screenshot 2024-05-21 at 11-36-36 Edit Works TEI records](https://github.com/majlis-erc/manuForma/assets/73166992/53de301f-1df3-453a-8cfc-539ed26b03c5)

**Comment by wsalesky** [comment]
@mMoliere Part of the problem is that the form expects the following: 
```
<author>
              <forename/>
              <surname/>
</author>
```

In other parts of the app, the author lookup requires 
`<author ref="https://jalit.org/person/18">Abraham al-Harzilānī</author>`

I can make a special call for authors with forename and surname, but it would be cleaner code to just change the expectation for the author element in the work record to accept a text node and have no children. This would happen in the schema. 

What do you think?

**Comment by mMoliere** [comment]
@wsalesky I agree that a clean solution is preferable. But the schema for works already specifies that the content of `<author>` can only be a `<textNode>`.

https://github.com/majlis-erc/manuForma/blob/bc19b7519b5d7037ba28b89062a098b1551b5960/forms/schemas/work-schema.xml#L294-L305

**Comment by wsalesky** [comment]
@mMoliere Sorry, I must not have updated my version of the schema. 
Please merge this: 
https://github.com/majlis-erc/manuForma/pull/627

And let me know if the issue is resolved.

**Comment by mMoliere** [comment]
@wsalesky I'm afraid the error is still there.

**Comment by mMoliere** [comment]
@wsalesky Update, I'm experiencing the same problem with manuscripts.

**Comment by wsalesky** [comment]
Try this please: https://github.com/majlis-erc/manuForma/pull/630

**Comment by mMoliere** [comment]
The error is still there

**Comment by wsalesky** [comment]
@mMoliere did you regenerate the Work form? It looks like the version on the server is the old one.

**Comment by mMoliere** [comment]
@wsalesky You're right, I forgot to refresh the works forms. I was distracted from the other bug. Thank you, it works!
