### ISSUE TITLE
Relations: Error

### ISSUE THREAD

**Issue by mMoliere** [majlis-erc/manuForma#699]
@wsalesky There is an error message in Relations that I can't sort out. Can you please take a look?

![Screenshot 2024-11-25 at 15-47-23 Edit Relation TEI Records](https://github.com/user-attachments/assets/ec5675f5-2b16-447d-b4a5-47533d10b814)

**Comment by mMoliere** [comment]
@wsalesky I have followed your suggestion, deleted the relationsTEI folder and rebuilt it by running the config file again. After merging the changes the error is indeed gone. But critically, the lookups for subject, object and mutuals are also missing. This puzzles me, since I made no changes to the config file.

**Comment by wsalesky** [comment]
I will take a look. On Dec 10, 2024, at 2:36 PM, mMoliere ***@***.***> wrote:﻿
@wsalesky I have followed your suggestion, deleted the relationsTEI folder and rebuilt it by running the config file again. After merging the changes the error is indeed gone. But critically, the lookups for subject, object and mutuals are also missing. This puzzles me, since I made no changes to the config file.

**Comment by mMoliere** [comment]
@wsalesky We are getting closer. It is displaying the lookup button. When click it the window is mostly empty:

![Screenshot 2024-12-11 at 21-29-49 Edit Relation TEI Records](https://github.com/user-attachments/assets/91f15648-014f-4b14-b8c2-21b9fc50bae9)

**Comment by wsalesky** [comment]
Try this: https://github.com/majlis-erc/manuForma/pull/715

**Comment by mMoliere** [comment]
@wsalesky Looks great! Thank you!
