### ISSUE TITLE
Codicological definition

### ISSUE THREAD

**Issue by mMoliere** [majlis-erc/manuForma#95]
The "Codicological definition" section is an oddity: it uses the `objectDesc` element which has a great many child elements that we break down into many other sections. But we need to access it to define the type of manuscript: it is either created as one artifact containing one text (single), one artifact containing multiple texts (multiple) or composed of individual artifacts that have been bound together (composite).

We have the following requests:

1. We would like to display the descriptions of the `@form `as a mouse over.
2. The values of `@form` should be available as a dropdown.
3. We don't want to see the "ghost child elements".

![Screenshot 2023-03-28 at 10-29-24 Edit MS TEI Records](https://user-images.githubusercontent.com/73166992/228179899-39678088-c3a3-4dbf-b4b7-a987dcabf9b6.png)

**Comment by wsalesky** [comment]
@mMoliere I think this has a similar problem to the Reproductions issue (https://github.com/majlis-erc/manuForma/issues/97), I do not see this element defined in the schema. Am I missing it?

**Comment by mMoliere** [comment]
@wsalesky I don't follow. `objectDesc` is the only element defined in the schema.

**Comment by wsalesky** [comment]
@mMoliere only objectDesc is defined in the schema, but the XML template has child elements, for example: https://github.com/majlis-erc/manuForma/blob/main/forms/templates/full-mss-template.xml#L110

Since the 'ghost elements' have no schema definition the form does not know what to do with them. Supressing them from the display causes some poor behavior in the up/down arrow functions, so it would be better to just remove them from the template.

**Comment by mMoliere** [comment]
@wsalesky Right, `objectDesc` has child element in the full template. And deleting them from it will not have side effects? How will manuForma know where to place `layoutDesc`?

**Comment by wsalesky** [comment]
@mMoliere The forms do not work that way. Because they are automatically generated, you have to keep parent and child elements together. I can not separate out just the objectDesc and not the children.
